import {
  GraphMemoryState,
  MemoryNodeKind,
  EdgeRelationType,
  SUPPORTED_AGENT_MODELS,
  CustomWorkflow,
} from '../src/types/memory.ts';

export function estimateTokens(text: string): number {
  return Math.max(8, Math.ceil(text.trim().length / 3.8));
}

export const DEFAULT_WORKFLOWS: CustomWorkflow[] = [
  {
    id: 'wf_cross_model_audit',
    name: 'Claude → ChatGPT Architecture & Security Relay',
    description:
      'Step 1 (Atlas on Claude 3.7) audits Gateway & Storage topology; Step 2 (Cipher on GPT-4o) verifies Zero-Trust leases and commits unified compliance rules.',
    createdAt: '2026-10-08T07:00:00Z',
    stages: [
      {
        id: 'stage_1',
        agentId: 'agent_atlas',
        modelOverrideId: 'claude-3-7-sonnet',
        instruction:
          'Inspect Service Topology (sub_arch) and Graph Paging Engine (sub_storage), verify Envoy 150ms circuit breaker alignment, and commit any missing architectural links.',
        autoReleaseAfterStage: true,
      },
      {
        id: 'stage_2',
        agentId: 'agent_cipher',
        modelOverrideId: 'gpt-4o',
        instruction:
          'Check out Zero-Trust Auth (sub_sec) and Incident Ledger (sub_sre), verify Ed25519 lease expiry protects against INC-409 saturation, and update the security summary.',
        autoReleaseAfterStage: true,
      },
    ],
  },
  {
    id: 'wf_incident_to_product',
    name: 'Incident Triage → SLA & Cost Governance Pipeline',
    description:
      'Step 1 (Nova on Gemini 3.8 Flash) triages SRE runbooks; Step 2 (Vanguard on o3-mini) updates enterprise SLA & token budget constraints.',
    createdAt: '2026-10-08T07:10:00Z',
    stages: [
      {
        id: 'stage_sre',
        agentId: 'agent_nova',
        modelOverrideId: 'gemini-3.8-flash',
        instruction:
          'Pull Incident Ledger (sub_sre), document automated connection draining for high-concurrency tenant bursts, and commit a new Procedure node.',
        autoReleaseAfterStage: true,
      },
      {
        id: 'stage_prod',
        agentId: 'agent_vanguard',
        modelOverrideId: 'o3-mini',
        instruction:
          'Pull Product & Tenant Governance (sub_product), link the new SRE draining procedure to the $0.004/turn cost ceiling, and update the executive summary.',
        autoReleaseAfterStage: true,
      },
    ],
  },
];

export const INITIAL_GRAPH_STATE: GraphMemoryState = {
  rootGraphId: 'engram_main_context',
  rootGraphName: 'Enterprise Cloud Architecture Graph',
  rootGraphDescription:
    'Production FalkorDB context graph decoupling corporate knowledge, sub-topics, and reasoning paths from individual LLMs.',
  falkorConnected: false,
  falkorEndpoint:
    (typeof process !== 'undefined' && process.env?.FALKORDB_URL) ||
    'embedded://falkordb-cypher-engine',
  availableModels: structuredClone(SUPPORTED_AGENT_MODELS),
  workflows: structuredClone(DEFAULT_WORKFLOWS),
  subtopics: [
    {
      id: 'sub_arch',
      name: 'Service Topology & Gateway',
      domain: 'Infrastructure & Routing',
      color: '#10B981',
      summary:
        'Defines the regional Envoy API gateway, gRPC worker mesh, and FalkorDB multigraph tenant isolation boundaries. Enforces 150ms upstream timeout budgets and strict circuit breaking on cross-region hops.',
      version: 3,
      updatedAt: '2026-10-08T06:15:00Z',
      lastUpdatedBy: 'agent_atlas',
      lastUpdatedByModel: 'Claude 3.7 Sonnet',
      summaryTokenCount: 44,
      fullTokenCount: 382,
      activeLeases: [],
      revisionHistory: [
        {
          version: 1,
          summary: 'Initial monolith to microservices routing map with single Redis cache.',
          updatedByAgentId: 'agent_atlas',
          authoredByModel: 'ChatGPT (GPT-4o)',
          updatedAt: '2026-10-05T11:00:00Z',
          commitNote: 'Initial topology seed via GPT-4o',
        },
        {
          version: 2,
          summary: 'Migrated state layer to FalkorDB multigraph namespaces per tenant.',
          updatedByAgentId: 'agent_atlas',
          authoredByModel: 'Claude 3.7 Sonnet',
          updatedAt: '2026-10-07T14:20:00Z',
          commitNote: 'Switched Atlas to Claude 3.7 Sonnet; added multigraph isolation decision',
        },
        {
          version: 3,
          summary:
            'Defines the regional Envoy API gateway, gRPC worker mesh, and FalkorDB multigraph tenant isolation boundaries. Enforces 150ms upstream timeout budgets and strict circuit breaking on cross-region hops.',
          updatedByAgentId: 'agent_atlas',
          authoredByModel: 'Claude 3.7 Sonnet',
          updatedAt: '2026-10-08T06:15:00Z',
          commitNote: 'Added 150ms gRPC circuit breaker threshold',
        },
      ],
    },
    {
      id: 'sub_sec',
      name: 'Zero-Trust Auth & Guardrails',
      domain: 'Security & Compliance',
      color: '#F59E0B',
      summary:
        'Governs short-lived mTLS workload identities, Ed25519 JWT token verification at edge, and PII redaction rules before any agent writes episodic memory to graph storage.',
      version: 2,
      updatedAt: '2026-10-08T06:40:00Z',
      lastUpdatedBy: 'agent_cipher',
      lastUpdatedByModel: 'ChatGPT (GPT-4o)',
      summaryTokenCount: 38,
      fullTokenCount: 346,
      activeLeases: [],
      revisionHistory: [
        {
          version: 1,
          summary: 'Standard bearer token authentication and static RBAC role table.',
          updatedByAgentId: 'agent_cipher',
          authoredByModel: 'Claude 3.5 Haiku',
          updatedAt: '2026-10-06T09:10:00Z',
          commitNote: 'Baseline RBAC setup',
        },
        {
          version: 2,
          summary:
            'Governs short-lived mTLS workload identities, Ed25519 JWT token verification at edge, and PII redaction rules before any agent writes episodic memory to graph storage.',
          updatedByAgentId: 'agent_cipher',
          authoredByModel: 'ChatGPT (GPT-4o)',
          updatedAt: '2026-10-08T06:40:00Z',
          commitNote: 'Switched to ChatGPT (GPT-4o); enforced mandatory PII scrubber before graph commit',
        },
      ],
    },
    {
      id: 'sub_storage',
      name: 'Graph Paging & Indexing Engine',
      domain: 'Memory Storage Layer',
      color: '#38BDF8',
      summary:
        'Controls Cypher traversal budgets, model-agnostic context handoff checkpoints, and lazy sub-topic checkout leases. Limits uncompressed sub-topic size to 800 tokens before triggering automatic sub-topic splitting.',
      version: 4,
      updatedAt: '2026-10-08T07:05:00Z',
      lastUpdatedBy: 'agent_atlas',
      lastUpdatedByModel: 'Claude 3.7 Sonnet',
      summaryTokenCount: 46,
      fullTokenCount: 398,
      activeLeases: [],
      revisionHistory: [
        {
          version: 3,
          summary: 'Cypher traversal rules and HNSW index parameters for memory nodes.',
          updatedByAgentId: 'agent_atlas',
          authoredByModel: 'Gemini 3.8 Flash',
          updatedAt: '2026-10-07T18:00:00Z',
          commitNote: 'Added vector index parameters',
        },
        {
          version: 4,
          summary:
            'Controls Cypher traversal budgets, model-agnostic context handoff checkpoints, and lazy sub-topic checkout leases. Limits uncompressed sub-topic size to 800 tokens before triggering automatic sub-topic splitting.',
          updatedByAgentId: 'agent_atlas',
          authoredByModel: 'Claude 3.7 Sonnet',
          updatedAt: '2026-10-08T07:05:00Z',
          commitNote: 'Set 800-token threshold & model-agnostic path persistence',
        },
      ],
    },
    {
      id: 'sub_sre',
      name: 'Incident Ledger & SLA Runbooks',
      domain: 'Reliability & Operations',
      color: '#F43F5E',
      summary:
        'Tracks recent production incidents, root-cause chains, and automated remediation playbooks. Documents the Oct 07 connection pool saturation caused by unpaged bulk context queries.',
      version: 3,
      updatedAt: '2026-10-08T07:18:00Z',
      lastUpdatedBy: 'agent_nova',
      lastUpdatedByModel: 'Gemini 3.8 Flash',
      summaryTokenCount: 40,
      fullTokenCount: 365,
      activeLeases: [],
      revisionHistory: [
        {
          version: 2,
          summary: 'Runbooks for high CPU usage and replica lag recovery.',
          updatedByAgentId: 'agent_nova',
          authoredByModel: 'ChatGPT (GPT-4o)',
          updatedAt: '2026-10-06T22:00:00Z',
          commitNote: 'Added replica failover runbook',
        },
        {
          version: 3,
          summary:
            'Tracks recent production incidents, root-cause chains, and automated remediation playbooks. Documents the Oct 07 connection pool saturation caused by unpaged bulk context queries.',
          updatedByAgentId: 'agent_nova',
          authoredByModel: 'Gemini 3.8 Flash',
          updatedAt: '2026-10-08T07:18:00Z',
          commitNote: 'Logged INC-409 post-mortem and paging mitigation',
        },
      ],
    },
    {
      id: 'sub_product',
      name: 'Tenant Quotas & SLA Commitments',
      domain: 'Product & Customer Specs',
      color: '#A855F7',
      summary:
        'Captures enterprise tier concurrency guarantees, EU/APAC data residency locks, and cost-per-agent-turn budgets ($0.004 max per reasoning cycle via sub-topic summary paging).',
      version: 2,
      updatedAt: '2026-10-08T07:25:00Z',
      lastUpdatedBy: 'agent_vanguard',
      lastUpdatedByModel: 'ChatGPT (o3-mini)',
      summaryTokenCount: 41,
      fullTokenCount: 329,
      activeLeases: [],
      revisionHistory: [
        {
          version: 1,
          summary: 'Tiered pricing quotas and default rate limits for free vs pro workspaces.',
          updatedByAgentId: 'agent_vanguard',
          authoredByModel: 'Claude 3.7 Sonnet',
          updatedAt: '2026-10-05T16:30:00Z',
          commitNote: 'Initial product tier constraints',
        },
        {
          version: 2,
          summary:
            'Captures enterprise tier concurrency guarantees, EU/APAC data residency locks, and cost-per-agent-turn budgets ($0.004 max per reasoning cycle via sub-topic summary paging).',
          updatedByAgentId: 'agent_vanguard',
          authoredByModel: 'ChatGPT (o3-mini)',
          updatedAt: '2026-10-08T07:25:00Z',
          commitNote: 'Added $0.004 per-turn token budget target',
        },
      ],
    },
  ],
  nodes: [
    // sub_arch nodes
    {
      id: 'node_arch_1',
      subtopicId: 'sub_arch',
      title: 'Envoy Edge Gateway Timeout Budget',
      content:
        'All synchronous agent tool invocations routed through Envoy must complete within 150ms P99; long-running graph syntheses use async SSE streams.',
      kind: MemoryNodeKind.CONSTRAINT,
      confidence: 0.98,
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Claude 3.7 Sonnet',
      updatedAt: '2026-10-08T06:10:00Z',
      tokenCount: 96,
    },
    {
      id: 'node_arch_2',
      subtopicId: 'sub_arch',
      title: 'Multigraph Tenant Isolation Keying',
      content:
        'Each organization workspace maps to a dedicated FalkorDB graph key `tenant_{org_id}_memory` inside a shared cluster to guarantee zero cross-tenant traversal leakage.',
      kind: MemoryNodeKind.DECISION,
      confidence: 0.99,
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'ChatGPT (GPT-4o)',
      updatedAt: '2026-10-07T14:20:00Z',
      tokenCount: 104,
    },
    {
      id: 'node_arch_3',
      subtopicId: 'sub_arch',
      title: 'Model-Agnostic State Handoff Bus',
      content:
        'Agents never store state in LLM provider thread memory. Switching an agent between Claude, ChatGPT, and Gemini preserves all graph pointers, mounted sub-topics, and traversal paths.',
      kind: MemoryNodeKind.FACT,
      confidence: 0.99,
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Claude 3.7 Sonnet',
      updatedAt: '2026-10-08T06:15:00Z',
      tokenCount: 92,
    },
    {
      id: 'node_arch_4',
      subtopicId: 'sub_arch',
      title: 'Cross-Region Read Replica Routing',
      content:
        'Read-only `inspect_graph_index` queries hit local regional replicas (us-east, eu-central, ap-east), while `update_subtopic_graph` commits route to the primary writer.',
      kind: MemoryNodeKind.PROCEDURE,
      confidence: 0.95,
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Gemini 3.8 Flash',
      updatedAt: '2026-10-08T06:15:00Z',
      tokenCount: 90,
    },

    // sub_sec nodes
    {
      id: 'node_sec_1',
      subtopicId: 'sub_sec',
      title: 'Mandatory Pre-Commit PII Redaction',
      content:
        'Before any model (Claude, ChatGPT, or Gemini) executes `update_subtopic_graph`, all node content strings pass through deterministic PII scrubbing.',
      kind: MemoryNodeKind.CONSTRAINT,
      confidence: 0.99,
      createdByAgentId: 'agent_cipher',
      authoredByModel: 'ChatGPT (GPT-4o)',
      updatedAt: '2026-10-08T06:40:00Z',
      tokenCount: 94,
    },
    {
      id: 'node_sec_2',
      subtopicId: 'sub_sec',
      title: 'Ed25519 Ephemeral Agent Leases',
      content:
        'Checking out a sensitive sub-topic binds the lease to the Agent ID in FalkorDB rather than a single LLM API key, so hot-swapping models keeps the lease valid.',
      kind: MemoryNodeKind.DECISION,
      confidence: 0.97,
      createdByAgentId: 'agent_cipher',
      authoredByModel: 'Claude 3.7 Sonnet',
      updatedAt: '2026-10-07T19:00:00Z',
      tokenCount: 88,
    },
    {
      id: 'node_sec_3',
      subtopicId: 'sub_sec',
      title: 'Cypher Parameterization Enforcement',
      content:
        'Raw string interpolation inside agent-generated Cypher mutations is blocked at the driver proxy; all node properties must bind via structured `$params`.',
      kind: MemoryNodeKind.PROCEDURE,
      confidence: 0.99,
      createdByAgentId: 'agent_cipher',
      authoredByModel: 'ChatGPT (GPT-4o)',
      updatedAt: '2026-10-08T06:35:00Z',
      tokenCount: 84,
    },
    {
      id: 'node_sec_4',
      subtopicId: 'sub_sec',
      title: 'Blocked Unscoped Graph Dump Attempt',
      content:
        'On Oct 06, an unconfigured research agent attempted `MATCH (n) RETURN n` across all sub-topics; policy guardrails intercepted and forced summary-only index paging.',
      kind: MemoryNodeKind.EPISODE,
      confidence: 0.98,
      createdByAgentId: 'agent_cipher',
      authoredByModel: 'Claude 3.5 Haiku',
      updatedAt: '2026-10-06T15:12:00Z',
      tokenCount: 80,
    },

    // sub_storage nodes
    {
      id: 'node_stor_1',
      subtopicId: 'sub_storage',
      title: 'Summary-First Context Paging Protocol',
      content:
        'Agents hold only the RootGraph directory of SubTopic summaries (~200 tokens total). Full MemoryNode subgraphs are paged into working RAM solely upon explicit `checkout_subtopic` calls.',
      kind: MemoryNodeKind.DECISION,
      confidence: 1.0,
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Claude 3.7 Sonnet',
      updatedAt: '2026-10-08T07:05:00Z',
      tokenCount: 108,
    },
    {
      id: 'node_stor_2',
      subtopicId: 'sub_storage',
      title: 'Immediate Eviction via release_subtopic',
      content:
        'As soon as an agent completes reasoning or mutations on a checked-out sub-topic, it invokes `release_subtopic` to drop the full nodes from its prompt window and persist the updated summary.',
      kind: MemoryNodeKind.PROCEDURE,
      confidence: 0.99,
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'ChatGPT (GPT-4o)',
      updatedAt: '2026-10-08T07:05:00Z',
      tokenCount: 102,
    },
    {
      id: 'node_stor_3',
      subtopicId: 'sub_storage',
      title: '800-Token Sub-Topic Split Threshold',
      content:
        'When a single SubTopic accumulates more than 800 tokens of MemoryNodes, the coordinator splits it into two distinct sub-topics linked to the RootGraph.',
      kind: MemoryNodeKind.CONSTRAINT,
      confidence: 0.95,
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Gemini 3.8 Flash',
      updatedAt: '2026-10-08T07:05:00Z',
      tokenCount: 94,
    },
    {
      id: 'node_stor_4',
      subtopicId: 'sub_storage',
      title: 'Cross-Model Path & Checkpoint Continuity',
      content:
        'Multi-hop traversal paths (:TraversalPath) are persisted as first-class graph citizens. If an agent switches from Claude to ChatGPT mid-task, ChatGPT inherits the exact path and mounted sub-topics.',
      kind: MemoryNodeKind.FACT,
      confidence: 0.99,
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Claude 3.7 Sonnet',
      updatedAt: '2026-10-07T21:10:00Z',
      tokenCount: 94,
    },

    // sub_sre nodes
    {
      id: 'node_sre_1',
      subtopicId: 'sub_sre',
      title: 'INC-409: Context Window & Pool Saturation',
      content:
        'Prior to hierarchical sub-topic paging, 12 concurrent agents loaded the entire 18,000-token history on every turn, spiking LLM latency to 14.2s and exhausting worker pools.',
      kind: MemoryNodeKind.EPISODE,
      confidence: 0.99,
      createdByAgentId: 'agent_nova',
      authoredByModel: 'Gemini 3.8 Flash',
      updatedAt: '2026-10-08T07:18:00Z',
      tokenCount: 102,
    },
    {
      id: 'node_sre_2',
      subtopicId: 'sub_sre',
      title: 'Playbook: Stale Lease Garbage Collection',
      content:
        'If an agent crashes while holding a `HOLDING_CONTEXT` edge on a SubTopic for >5 minutes without heartbeats, the SRE sweeper detaches the lease and restores clean state.',
      kind: MemoryNodeKind.PROCEDURE,
      confidence: 0.96,
      createdByAgentId: 'agent_nova',
      authoredByModel: 'ChatGPT (GPT-4o)',
      updatedAt: '2026-10-08T07:18:00Z',
      tokenCount: 92,
    },
    {
      id: 'node_sre_3',
      subtopicId: 'sub_sre',
      title: 'Sub-Topic Paging Cut Token Spend by 84%',
      content:
        'Benchmarking after deploying `checkout_subtopic` + `release_subtopic` showed average active prompt context dropped from 1,820 tokens to 290 tokens per agent turn across Claude, GPT-4o, and Gemini.',
      kind: MemoryNodeKind.FACT,
      confidence: 0.99,
      createdByAgentId: 'agent_nova',
      authoredByModel: 'Gemini 3.8 Flash',
      updatedAt: '2026-10-08T07:18:00Z',
      tokenCount: 91,
    },
    {
      id: 'node_sre_4',
      subtopicId: 'sub_sre',
      title: '2-Hop Cross-Topic Traversal Guard',
      content:
        'Automated anomaly triage agents may traverse at most 2 cross-subtopic edges per step without requesting explicit human or coordinator elevation.',
      kind: MemoryNodeKind.CONSTRAINT,
      confidence: 0.94,
      createdByAgentId: 'agent_nova',
      authoredByModel: 'Claude 3.7 Sonnet',
      updatedAt: '2026-10-07T11:45:00Z',
      tokenCount: 80,
    },

    // sub_product nodes
    {
      id: 'node_prod_1',
      subtopicId: 'sub_product',
      title: 'Enterprise EU Data Residency Lock',
      content:
        'EU Healthcare & FinTech tenants require their FalkorDB multigraph namespace and sub-topic summaries to remain pinned to `eu-central-1` Frankfurt nodes.',
      kind: MemoryNodeKind.CONSTRAINT,
      confidence: 0.99,
      createdByAgentId: 'agent_vanguard',
      authoredByModel: 'Claude 3.7 Sonnet',
      updatedAt: '2026-10-08T07:25:00Z',
      tokenCount: 88,
    },
    {
      id: 'node_prod_2',
      subtopicId: 'sub_product',
      title: '$0.004 Maximum Cost Per Agent Turn',
      content:
        'Unit economics mandate that multi-agent workflows stay under $0.004 per turn by loading only 1–2 relevant sub-topics at any time instead of full-graph dumps.',
      kind: MemoryNodeKind.DECISION,
      confidence: 0.98,
      createdByAgentId: 'agent_vanguard',
      authoredByModel: 'ChatGPT (o3-mini)',
      updatedAt: '2026-10-08T07:25:00Z',
      tokenCount: 86,
    },
    {
      id: 'node_prod_3',
      subtopicId: 'sub_product',
      title: 'Audit Trail Explainability Requirement',
      content:
        'Enterprise customers require every agent action to log which LLM model and Agent ID checked out a SubTopic, which MemoryNodes were mutated, and the exact Cypher query.',
      kind: MemoryNodeKind.FACT,
      confidence: 0.97,
      createdByAgentId: 'agent_vanguard',
      authoredByModel: 'ChatGPT (GPT-4o)',
      updatedAt: '2026-10-07T16:00:00Z',
      tokenCount: 85,
    },
    {
      id: 'node_prod_4',
      subtopicId: 'sub_product',
      title: 'Multi-Agent Handoff SLA (<2.5s End-to-End)',
      content:
        'When Agent A (e.g., on Claude) finishes updating a sub-topic and releases it, Agent B (e.g., on ChatGPT) receives the updated SubTopic summary directory within 120ms.',
      kind: MemoryNodeKind.CONSTRAINT,
      confidence: 0.96,
      createdByAgentId: 'agent_vanguard',
      authoredByModel: 'ChatGPT (o3-mini)',
      updatedAt: '2026-10-08T07:25:00Z',
      tokenCount: 70,
    },
  ],
  edges: [
    {
      id: 'edge_1',
      sourceId: 'node_arch_3',
      targetId: 'node_arch_1',
      relation: EdgeRelationType.GOVERNED_BY,
      rationale: 'gRPC coordinator handoffs must respect the 150ms Envoy gateway budget.',
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Claude 3.7 Sonnet',
      createdAt: '2026-10-08T06:15:00Z',
    },
    {
      id: 'edge_2',
      sourceId: 'node_sec_4',
      targetId: 'node_sec_3',
      relation: EdgeRelationType.CAUSED_BY,
      rationale: 'Unscoped dump attempt prompted strict Cypher parameterization and query proxy guards.',
      createdByAgentId: 'agent_cipher',
      authoredByModel: 'ChatGPT (GPT-4o)',
      createdAt: '2026-10-08T06:35:00Z',
    },
    {
      id: 'edge_3',
      sourceId: 'node_stor_2',
      targetId: 'node_stor_1',
      relation: EdgeRelationType.DEPENDS_ON,
      rationale: 'Immediate release_subtopic eviction complements summary-first checkout paging.',
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Claude 3.7 Sonnet',
      createdAt: '2026-10-08T07:05:00Z',
    },
    {
      id: 'edge_4',
      sourceId: 'node_sre_3',
      targetId: 'node_sre_1',
      relation: EdgeRelationType.MITIGATES,
      rationale: '84% token reduction directly resolved the INC-409 context saturation outage.',
      createdByAgentId: 'agent_nova',
      authoredByModel: 'Gemini 3.8 Flash',
      createdAt: '2026-10-08T07:18:00Z',
    },
    {
      id: 'edge_cross_1',
      sourceId: 'node_stor_1',
      targetId: 'node_sre_1',
      relation: EdgeRelationType.MITIGATES,
      rationale: 'Summary-first context paging in Storage Engine eliminated INC-409 saturation.',
      createdByAgentId: 'agent_nova',
      authoredByModel: 'Gemini 3.8 Flash',
      createdAt: '2026-10-08T07:18:00Z',
    },
    {
      id: 'edge_cross_2',
      sourceId: 'node_prod_2',
      targetId: 'node_stor_1',
      relation: EdgeRelationType.DEPENDS_ON,
      rationale: '$0.004/turn unit cost relies on loading only sub-topic summaries by default.',
      createdByAgentId: 'agent_vanguard',
      authoredByModel: 'ChatGPT (o3-mini)',
      createdAt: '2026-10-08T07:25:00Z',
    },
    {
      id: 'edge_cross_3',
      sourceId: 'node_prod_1',
      targetId: 'node_arch_2',
      relation: EdgeRelationType.DEPENDS_ON,
      rationale: 'EU data residency lock leverages FalkorDB multigraph tenant isolation keys.',
      createdByAgentId: 'agent_vanguard',
      authoredByModel: 'Claude 3.7 Sonnet',
      createdAt: '2026-10-08T07:25:00Z',
    },
    {
      id: 'edge_cross_4',
      sourceId: 'node_sre_2',
      targetId: 'node_sec_2',
      relation: EdgeRelationType.RELATES_TO,
      rationale: 'SRE stale lease garbage collection enforces Cipher Ed25519 lease expiry.',
      createdByAgentId: 'agent_cipher',
      authoredByModel: 'ChatGPT (GPT-4o)',
      createdAt: '2026-10-08T07:20:00Z',
    },
  ],
  savedPaths: [
    {
      id: 'path_cost_to_outage',
      title: 'Unit Cost → Summary Paging → INC-409 Mitigation Path',
      description:
        '3-hop cross-subtopic reasoning path connecting Product ($0.004/turn budget) → Storage (Summary-First Paging) → SRE (INC-409 Pool Saturation Mitigation). Persisted in FalkorDB so any model (Claude, ChatGPT, Gemini) can resume traversal immediately.',
      subtopicIds: ['sub_product', 'sub_storage', 'sub_sre'],
      nodeIds: ['node_prod_2', 'node_stor_1', 'node_sre_1', 'node_sre_3'],
      edgeIds: ['edge_cross_2', 'edge_cross_1', 'edge_4'],
      createdByAgentId: 'agent_atlas',
      authoredByModel: 'Claude 3.7 Sonnet',
      createdAt: '2026-10-08T07:19:00Z',
    },
    {
      id: 'path_residency_isolation',
      title: 'EU Residency Lock → Multigraph Isolation → Gateway Timeout Path',
      description:
        'Cross-domain compliance path linking EU Healthcare Residency (sub_product) to FalkorDB Multigraph Keying (sub_arch) and Envoy 150ms Timeout Constraints.',
      subtopicIds: ['sub_product', 'sub_arch'],
      nodeIds: ['node_prod_1', 'node_arch_2', 'node_arch_3', 'node_arch_1'],
      edgeIds: ['edge_cross_3', 'edge_1'],
      createdByAgentId: 'agent_vanguard',
      authoredByModel: 'ChatGPT (GPT-4o)',
      createdAt: '2026-10-08T07:25:00Z',
    },
    {
      id: 'path_lease_recovery',
      title: 'SRE Stale Lease GC → Ed25519 Ephemeral Lease Security Path',
      description:
        'Operational security path traced across Incident Runbooks (sub_sre) and Zero-Trust Auth (sub_sec) ensuring model switches never orphan or leak sub-topic leases.',
      subtopicIds: ['sub_sre', 'sub_sec'],
      nodeIds: ['node_sre_2', 'node_sec_2', 'node_sec_3'],
      edgeIds: ['edge_cross_4'],
      createdByAgentId: 'agent_cipher',
      authoredByModel: 'Gemini 3.8 Flash',
      createdAt: '2026-10-08T07:28:00Z',
    },
  ],
  agents: [
    {
      id: 'agent_atlas',
      name: 'Atlas',
      role: 'Topology & Storage Architect',
      specialty: 'Service routing, FalkorDB multigraph schema, and sub-topic partitioning',
      accentColor: '#10B981',
      activeModelId: 'claude-3-7-sonnet',
      activeModelLabel: 'Claude 3.7 Sonnet',
      activeProvider: 'Anthropic Claude',
      modelSwitchCount: 2,
      status: 'idle',
      mountedSubtopicIds: [],
      activePathIds: ['path_cost_to_outage'],
      totalTasksCompleted: 14,
      totalCommits: 9,
      lastActiveAt: '2026-10-08T07:05:00Z',
    },
    {
      id: 'agent_cipher',
      name: 'Cipher',
      role: 'Security & Guardrail Auditor',
      specialty: 'Zero-trust leases, PII scrubbing, and Cypher query safety',
      accentColor: '#F59E0B',
      activeModelId: 'gpt-4o',
      activeModelLabel: 'ChatGPT (GPT-4o)',
      activeProvider: 'OpenAI ChatGPT',
      modelSwitchCount: 1,
      status: 'idle',
      mountedSubtopicIds: [],
      activePathIds: ['path_lease_recovery'],
      totalTasksCompleted: 11,
      totalCommits: 6,
      lastActiveAt: '2026-10-08T06:40:00Z',
    },
    {
      id: 'agent_nova',
      name: 'Nova',
      role: 'SRE & Incident Responder',
      specialty: 'Root-cause graph traversal, lease eviction, and latency mitigations',
      accentColor: '#F43F5E',
      activeModelId: 'gemini-3.8-flash',
      activeModelLabel: 'Gemini 3.8 Flash',
      activeProvider: 'Google Gemini',
      modelSwitchCount: 1,
      status: 'idle',
      mountedSubtopicIds: [],
      activePathIds: ['path_cost_to_outage', 'path_lease_recovery'],
      totalTasksCompleted: 19,
      totalCommits: 12,
      lastActiveAt: '2026-10-08T07:18:00Z',
    },
    {
      id: 'agent_vanguard',
      name: 'Vanguard',
      role: 'Product & Tenant Coordinator',
      specialty: 'SLA governance, token budget optimization, and cross-team handoffs',
      accentColor: '#A855F7',
      activeModelId: 'o3-mini',
      activeModelLabel: 'ChatGPT (o3-mini)',
      activeProvider: 'OpenAI ChatGPT',
      modelSwitchCount: 1,
      status: 'idle',
      mountedSubtopicIds: [],
      activePathIds: ['path_residency_isolation'],
      totalTasksCompleted: 8,
      totalCommits: 5,
      lastActiveAt: '2026-10-08T07:25:00Z',
    },
  ],
  traceHistory: [
    {
      id: 'trace_seed_1',
      stepNumber: 1,
      timestamp: '2026-10-08T07:16:02Z',
      agentId: 'agent_nova',
      agentName: 'Nova',
      activeModel: 'ChatGPT (GPT-4o)',
      phase: 'INDEX_SCAN',
      summary: 'Loaded RootGraph handle & 5 Sub-Topic summaries (209 tokens). 0 full sub-topics mounted.',
      detail:
        'Nova (running on ChatGPT GPT-4o) inspected the Sub-Topic Summary Directory to locate context relevant to INC-409 connection pool saturation.',
      cypherQuery: `MATCH (g:RootGraph {id: 'engram_main_context'})-[:HAS_SUBTOPIC]->(s:SubTopic)\nRETURN s.id, s.name, s.domain, s.summary, s.version ORDER BY s.id`,
      activeTokensBefore: 209,
      activeTokensAfter: 209,
    },
    {
      id: 'trace_seed_2',
      stepNumber: 2,
      timestamp: '2026-10-08T07:16:08Z',
      agentId: 'agent_nova',
      agentName: 'Nova',
      activeModel: 'ChatGPT (GPT-4o)',
      phase: 'PAGE_IN_CHECKOUT',
      subtopicId: 'sub_sre',
      subtopicName: 'Incident Ledger & SLA Runbooks',
      summary: 'Paged in Sub-Topic [sub_sre] into active working memory (+365 tokens).',
      detail:
        'Nova requested full MemoryNodes inside sub_sre while keeping the other 4 sub-topics unloaded in the graph.',
      cypherQuery: `MATCH (a:Agent {id: 'agent_nova'}), (s:SubTopic {id: 'sub_sre'})\nMERGE (a)-[:HOLDING_CONTEXT {checkedOutAt: '2026-10-08T07:16:08Z', activeModel: 'ChatGPT (GPT-4o)'}]->(s)\nWITH s MATCH (s)-[:CONTAINS_MEMORY]->(m:MemoryNode)\nOPTIONAL MATCH (m)-[r]->(t:MemoryNode)\nRETURN s, collect(m) AS nodes, collect(r) AS edges`,
      activeTokensBefore: 209,
      activeTokensAfter: 574,
    },
    {
      id: 'trace_seed_swap',
      stepNumber: 3,
      timestamp: '2026-10-08T07:17:05Z',
      agentId: 'agent_nova',
      agentName: 'Nova',
      activeModel: 'Gemini 3.8 Flash',
      phase: 'MODEL_HOT_SWAP',
      subtopicId: 'sub_sre',
      subtopicName: 'Incident Ledger & SLA Runbooks',
      summary: 'Hot-swapped Nova model: ChatGPT (GPT-4o) → Gemini 3.8 Flash (0 tokens lost; leases & paths preserved).',
      detail:
        'Because state lives in FalkorDB rather than LLM thread memory, Gemini 3.8 Flash inherited the active sub_sre lease, all 5 sub-topic summaries, and 2 traversal paths without re-fetching.',
      cypherQuery: `MATCH (a:Agent {id: 'agent_nova'})\nSET a.activeModelId = 'gemini-3.8-flash', a.activeModelLabel = 'Gemini 3.8 Flash', a.modelSwitchCount = a.modelSwitchCount + 1\nWITH a OPTIONAL MATCH (a)-[lease:HOLDING_CONTEXT]->(s:SubTopic)\nSET lease.activeModel = 'Gemini 3.8 Flash'\nRETURN a.id, a.activeModelLabel, collect(s.id) AS preservedSubtopicLeases`,
      activeTokensBefore: 574,
      activeTokensAfter: 574,
    },
    {
      id: 'trace_seed_3',
      stepNumber: 4,
      timestamp: '2026-10-08T07:17:40Z',
      agentId: 'agent_nova',
      agentName: 'Nova',
      activeModel: 'Gemini 3.8 Flash',
      phase: 'GRAPH_COMMIT',
      subtopicId: 'sub_sre',
      subtopicName: 'Incident Ledger & SLA Runbooks',
      summary: 'Updated [sub_sre] graph with 84% token reduction metric & bumped summary to v3.',
      detail:
        'Nova (now on Gemini 3.8 Flash) committed MemoryNode [node_sre_3], linked it via [:MITIGATES] to [node_sre_1], and regenerated the sub_sre executive summary.',
      cypherQuery: `MATCH (s:SubTopic {id: 'sub_sre'})\nCREATE (s)-[:CONTAINS_MEMORY]->(m:MemoryNode {id: 'node_sre_3', kind: 'Fact', authoredByModel: 'Gemini 3.8 Flash', title: 'Sub-Topic Paging Cut Token Spend by 84%'})\nWITH s, m MATCH (inc:MemoryNode {id: 'node_sre_1'})\nMERGE (m)-[:MITIGATES]->(inc)\nSET s.summary = $updatedSummary, s.version = s.version + 1, s.lastUpdatedByModel = 'Gemini 3.8 Flash'`,
      activeTokensBefore: 574,
      activeTokensAfter: 574,
    },
    {
      id: 'trace_seed_4',
      stepNumber: 5,
      timestamp: '2026-10-08T07:18:00Z',
      agentId: 'agent_nova',
      agentName: 'Nova',
      activeModel: 'Gemini 3.8 Flash',
      phase: 'PAGE_OUT_RELEASE',
      subtopicId: 'sub_sre',
      subtopicName: 'Incident Ledger & SLA Runbooks',
      summary: 'Evicted [sub_sre] back to FalkorDB (-365 tokens). Active context reset to 209 tokens.',
      detail:
        'After completing the incident update, Nova released the sub_sre context lease so its working memory returned to holding only the graph summary index.',
      cypherQuery: `MATCH (a:Agent {id: 'agent_nova'})-[lease:HOLDING_CONTEXT]->(s:SubTopic {id: 'sub_sre'})\nDELETE lease\nRETURN a.id, s.id, s.version`,
      activeTokensBefore: 574,
      activeTokensAfter: 209,
    },
  ],
  runHistory: [],
};

export function createBlankWorkspaceState(params: {
  id: string;
  name: string;
  description: string;
}): GraphMemoryState {
  const now = new Date().toISOString();
  return {
    rootGraphId: params.id,
    rootGraphName: params.name,
    rootGraphDescription:
      params.description ||
      'Custom corporate multi-agent graph workspace with hierarchical sub-topic paging.',
    falkorConnected: false,
    falkorEndpoint:
      (typeof process !== 'undefined' && process.env?.FALKORDB_URL) ||
      'embedded://falkordb-cypher-engine',
    availableModels: structuredClone(SUPPORTED_AGENT_MODELS),
    workflows: [],
    subtopics: [
      {
        id: 'sub_core',
        name: 'Core Architecture & Context',
        domain: 'Primary Knowledge',
        color: '#10B981',
        summary:
          'Initial root sub-topic partition for this workspace. Ingest documents, add custom sub-topics, or run agents to populate nodes.',
        version: 1,
        updatedAt: now,
        lastUpdatedBy: 'agent_lead',
        lastUpdatedByModel: 'Claude 3.7 Sonnet',
        summaryTokenCount: 28,
        fullTokenCount: 64,
        activeLeases: [],
        revisionHistory: [
          {
            version: 1,
            summary:
              'Initial root sub-topic partition for this workspace. Ingest documents, add custom sub-topics, or run agents to populate nodes.',
            updatedByAgentId: 'agent_lead',
            authoredByModel: 'Claude 3.7 Sonnet',
            updatedAt: now,
            commitNote: 'Workspace initialized',
          },
        ],
      },
    ],
    nodes: [
      {
        id: 'node_welcome_1',
        subtopicId: 'sub_core',
        title: 'Workspace Root Anchor',
        content: `Workspace "${params.name}" initialized. Use "Ingest Docs" to auto-partition company documentation into graph sub-topics or connect external agents via the REST / MCP API.`,
        kind: MemoryNodeKind.FACT,
        confidence: 1.0,
        createdByAgentId: 'agent_lead',
        authoredByModel: 'Claude 3.7 Sonnet',
        updatedAt: now,
        tokenCount: 36,
      },
    ],
    edges: [],
    savedPaths: [],
    agents: [
      {
        id: 'agent_lead',
        name: 'Architect',
        role: 'Lead Systems Agent',
        specialty: 'Knowledge partitioning, graph updates, and cross-topic synthesis',
        accentColor: '#10B981',
        activeModelId: 'claude-3-7-sonnet',
        activeModelLabel: 'Claude 3.7 Sonnet',
        activeProvider: 'Anthropic Claude',
        modelSwitchCount: 0,
        status: 'idle',
        mountedSubtopicIds: [],
        activePathIds: [],
        totalTasksCompleted: 0,
        totalCommits: 1,
        lastActiveAt: now,
      },
      {
        id: 'agent_reviewer',
        name: 'Verifier',
        role: 'Compliance & QA Agent',
        specialty: 'Constraint verification, edge validation, and summary auditing',
        accentColor: '#38BDF8',
        activeModelId: 'gpt-4o',
        activeModelLabel: 'ChatGPT (GPT-4o)',
        activeProvider: 'OpenAI ChatGPT',
        modelSwitchCount: 0,
        status: 'idle',
        mountedSubtopicIds: [],
        activePathIds: [],
        totalTasksCompleted: 0,
        totalCommits: 0,
        lastActiveAt: now,
      },
    ],
    traceHistory: [
      {
        id: `trace_init_${Date.now()}`,
        stepNumber: 1,
        timestamp: now,
        agentId: 'agent_lead',
        agentName: 'Architect',
        activeModel: 'Claude 3.7 Sonnet',
        phase: 'INDEX_SCAN',
        summary: `Initialized workspace [${params.name}] with 1 root sub-topic.`,
        detail: 'Ready for document ingestion, custom agent workflows, and external SDK requests.',
        cypherQuery: `CREATE (g:RootGraph {id: '${params.id}', name: ${JSON.stringify(params.name)}})-[:HAS_SUBTOPIC]->(:SubTopic {id: 'sub_core', name: 'Core Architecture & Context', version: 1})`,
        activeTokensBefore: 28,
        activeTokensAfter: 28,
      },
    ],
    runHistory: [],
  };
}

